version: '3.8'

services:
  app1:
    build:
      context: ./app1
    ports:
      - '4000:4000'
    networks:
      - tp3
  app2:
    build:
      context: ./app2
    ports:
      - '4001:4001'
    networks:
      - tp3
    depends_on:
      - app1

networks:
  tp3:
    driver: bridge
    name: tp3